'use strict';
// Shared deterministic game rules. The same source is embedded in the browser build.
const Game=(()=>{
const N=64,Y=32,DAY_MS=8*60*1000,idx=(x,y,z)=>x+N*(z+N*y),key=(x,y,z)=>`${x},${y},${z}`;
const OPEN_DOORS=new Set([12,16,19,21]);
const SOLID_DECOR=new Set([11,15,18,20]);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fract=v=>v-Math.floor(v),smooth=t=>t*t*(3-2*t);
function hash3(x,y,z){return fract(Math.sin(x*127.1+y*311.7+z*74.7)*43758.5453123)}
function hash2(x,z){return hash3(x,0,z)}
function noise3(x,y,z){const xi=Math.floor(x),yi=Math.floor(y),zi=Math.floor(z),xf=smooth(fract(x)),yf=smooth(fract(y)),zf=smooth(fract(z));const h=(dx,dy,dz)=>hash3(xi+dx,yi+dy,zi+dz),mix=(a,b,t)=>a+(b-a)*t;const x00=mix(h(0,0,0),h(1,0,0),xf),x10=mix(h(0,1,0),h(1,1,0),xf),x01=mix(h(0,0,1),h(1,0,1),xf),x11=mix(h(0,1,1),h(1,1,1),xf);return mix(mix(x00,x10,yf),mix(x01,x11,yf),zf)}
function noise2(x,z){return noise3(x,0,z)}
const height=(x,z)=>Math.floor(7+2.7*Math.sin(x*.13)+2.1*Math.cos(z*.16)+1.4*Math.sin((x+z)*.22));
function entranceAt(x,z){const gx=Math.floor(x/32),gz=Math.floor(z/32),cx=gx*32+8+Math.floor(hash2(gx*3+11,gz*5-7)*16),cz=gz*32+8+Math.floor(hash2(gx*7-2,gz*3+17)*16),dx=x-cx,dz=z-cz;return dx*dx+dz*dz<2.7}
function caveAir(x,y,z,h=height(x,z)){
 if(y<2||y>h)return false;
 const depth=h-y;
 if(entranceAt(x,z)&&depth<=6)return true; // vertical entrance connecting surface to the network
 if(depth<2)return false;
 const a=noise3(x*.085,y*.13,z*.085),b=noise3(x*.17+31,y*.19-13,z*.17+9),c=noise3(x*.043-8,y*.075+19,z*.043+27);
 const tunnel=Math.abs(a-.51)<(.10+.035*c)&&b>.38;
 const chamber=a>.66&&c>.59&&b>.46;
 return tunnel||chamber;
}
function adjacentCave(x,y,z,h){return caveAir(x+1,y,z,height(x+1,z))||caveAir(x-1,y,z,height(x-1,z))||caveAir(x,y+1,z,h)||caveAir(x,y-1,z,h)||caveAir(x,y,z+1,height(x,z+1))||caveAir(x,y,z-1,height(x,z-1))}
function oreAt(x,y,z,h){if(y<2||y>h-3||!adjacentCave(x,y,z,h))return 0;const n=noise3(x*.31+101,y*.31+17,z*.31-73);if(y<=6&&n>.84)return 27;if(y<=10&&n>.78)return 26;if(y<=16&&n>.71)return 25;if(n>.64)return 24;return 0}
function groundTerrain(x,y,z){if(y<0||y>=Y)return 0;const h=height(x,z);if(y>h){if(h<5&&y<=5)return 43;return 0}if(caveAir(x,y,z,h))return 0;if(y===h)return h<5?6:1;if(y>h-3)return h<5?6:2;const ore=oreAt(x,y,z,h);return ore||3}
function treeTypeAt(tx,tz){return Math.sin(tx*23+tz*37)>.15&&Math.hypot(tx-32,tz-32)>6&&height(tx,tz)>=5&&!entranceAt(tx,tz)}
function treeOverlay(x,y,z){let b=0;for(let tx=4+5*Math.ceil((x-6)/5);tx<=x+2;tx+=5)for(let tz=4+5*Math.ceil((z-6)/5);tz<=z+2;tz+=5){if(!treeTypeAt(tx,tz))continue;const th=height(tx,tz),dy=y-th;if(tx===x&&tz===z&&dy>=1&&dy<=4)b=4;if(Math.abs(x-tx)+Math.abs(z-tz)<4&&dy>=3&&dy<=5)b=5;if(tx===x&&tz===z&&dy===3)b=4}return b}
function naturalTerrain(x,y,z){const g=groundTerrain(x,y,z);if(g)return g;if(y<=height(x,z))return 0;return treeOverlay(x,y,z)}
const base=new Uint8Array(N*N*Y);function put(x,y,z,b){if(x>=0&&z>=0&&y>=0&&x<N&&z<N&&y<Y)base[idx(x,y,z)]=b}
for(let x=0;x<N;x++)for(let z=0;z<N;z++)for(let y=0;y<Y;y++)put(x,y,z,naturalTerrain(x,y,z));
function terrain(x,y,z){if(y<0||y>=Y)return 0;if(x>=0&&x<N&&z>=0&&z<N)return base[idx(x,y,z)];return naturalTerrain(x,y,z)}
function get(s,x,y,z){return s.blocks[key(x,y,z)]?.b??terrain(x,y,z)}
function block(s,x,y,z,b,natural=false){s.blocks[key(x,y,z)]={x,y,z,b,id:s.rev,natural}}
function isSolid(s,x,y,z){const b=get(s,x,y,z);return b!==0&&!OPEN_DOORS.has(b)&&b!==17&&![30,43,44].includes(b)}
function clearLine(s,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2],len=Math.hypot(dx,dy,dz);if(len<.01)return true;const steps=Math.ceil(len/.22);for(let i=1;i<steps;i++){const t=i/steps,x=a[0]+dx*t,y=a[1]+dy*t,z=a[2]+dz*t;if(isSolid(s,Math.floor(x),Math.floor(y),Math.floor(z)))return false}return true}
function ensureWorld(s,now=Date.now()){if(!Number.isFinite(s.worldEpoch))s.worldEpoch=now-DAY_MS*.23;s.arrows=s.arrows||{};s.arrowSeq=Number.isFinite(s.arrowSeq)?s.arrowSeq:0}
function timeInfo(s,now=Date.now()){ensureWorld(s,now);const phase=((now-s.worldEpoch)%DAY_MS+DAY_MS)%DAY_MS/DAY_MS,sun=Math.sin(phase*Math.PI*2),twilight=clamp((sun+.22)/.42,0,1),light=.17+.83*(twilight*twilight*(3-2*twilight)),isNight=phase>=.56&&phase<.94;let label=phase<.08?'Рассвет':phase<.46?'День':phase<.56?'Закат':phase<.94?'Ночь':'Рассвет';return {phase,light,isNight,label,day:Math.floor((now-s.worldEpoch)/DAY_MS)+1,dayMs:DAY_MS,epoch:s.worldEpoch}}

const MOB_DEFS={
 zombie:{name:'Зомби',hp:16,speed:1.05,damage:2,range:1.45,verticalReach:1.25,cooldown:1200,hostile:true},
 skeleton:{name:'Скелет',hp:14,speed:.78,damage:2,range:9,verticalReach:8,cooldown:2300,hostile:true,ranged:true},
 spider:{name:'Паук',hp:12,speed:1.55,damage:2,range:1.25,verticalReach:.65,cooldown:950,hostile:true},
 cow:{name:'Корова',hp:12,speed:.45,damage:0,range:0,verticalReach:0,cooldown:0,hostile:false},
 sheep:{name:'Овца',hp:10,speed:.42,damage:0,range:0,verticalReach:0,cooldown:0,hostile:false},
 pig:{name:'Свинья',hp:10,speed:.5,damage:0,range:0,verticalReach:0,cooldown:0,hostile:false}
};
const MOB_PRESETS=[['cow',25,25],['cow',38,22],['cow',45,42],['sheep',20,40],['sheep',35,48],['sheep',50,30],['pig',15,20],['pig',42,15],['pig',52,50]];
function mobGround(x,z){const ix=Math.floor(x),iz=Math.floor(z);for(let y=Math.min(Y-2,height(ix,iz)+1);y>=1;y--){const b=terrain(ix,y,iz);if(b&&b!==5)return y+1.05}return 2.05}
function mobSpaceClear(s,x,y,z,type){const ix=Math.floor(x),iz=Math.floor(z),top=type==='spider'?.42:1.65;for(let yy=Math.floor(y+.02);yy<=Math.floor(y+top-.02);yy++)if(isSolid(s,ix,yy,iz))return false;return true}
function spawnMob(s,type,x,z,nightSpawn=false){const d=MOB_DEFS[type];if(!d)return null;const id='m'+(++s.mobSeq),y=mobGround(x,z),m={id,type,x,z,y,yaw:0,hp:d.hp,maxHp:d.hp,spawnX:x,spawnZ:z,lastAttack:0,respawnAt:0,nightSpawn};s.mobs[id]=m;return m}
function ensureMobs(s){ensureWorld(s);s.mobs=s.mobs||{};s.mobSeq=Number.isFinite(s.mobSeq)?s.mobSeq:0;if(!Object.values(s.mobs).some(m=>!MOB_DEFS[m.type]?.hostile)){for(const [type,x,z]of MOB_PRESETS)spawnMob(s,type,x+.5,z+.5,false)}}
function manageNightMobs(s,now,players){const night=timeInfo(s,now).isNight;const hostiles=Object.values(s.mobs).filter(m=>MOB_DEFS[m.type]?.hostile);if(!night){for(const m of hostiles)delete s.mobs[m.id];return}if(now-(s.lastNightSpawn||0)<1800||hostiles.length>=12)return;const active=players.filter(p=>p&&p.active&&validPos(p.position)&&!player(s,p.id,now).dead);if(!active.length)return;s.lastNightSpawn=now;const p=active[s.mobSeq%active.length],seed=hash3(s.mobSeq+Math.floor(now/1800),Math.floor(p.position[0]),Math.floor(p.position[2])),angle=seed*Math.PI*2,dist=8+hash3(s.mobSeq+19,7,11)*7,x=p.position[0]+Math.sin(angle)*dist,z=p.position[2]+Math.cos(angle)*dist,ix=Math.floor(x),iz=Math.floor(z),h=height(ix,iz);if(h<5||terrain(ix,h,iz)===0)return;const r=hash3(s.mobSeq+5,13,23),type=r<.45?'zombie':r<.72?'skeleton':'spider';spawnMob(s,type,x,z,true)}
function mobTick(s,now=Date.now(),players=[]){ensureMobs(s);manageNightMobs(s,now,players);const last=s.mobTickAt||now,dt=Math.min(.55,Math.max(0,(now-last)/1000));s.mobTickAt=now;if(dt<=0)return;for(const mob of Object.values(s.mobs)){const def=MOB_DEFS[mob.type];if(!def)continue;if(mob.hp<=0){if(!def.hostile&&now>=(mob.respawnAt||0)){mob.hp=def.hp;mob.maxHp=def.hp;mob.x=mob.spawnX;mob.z=mob.spawnZ;mob.y=mobGround(mob.x,mob.z);mob.respawnAt=0}continue}let nearest=null;for(const p of players){if(!p||!p.active||!validPos(p.position))continue;const bag=player(s,p.id,now);if(bag.dead)continue;const dx=p.position[0]-mob.x,dz=p.position[2]-mob.z,horiz=Math.hypot(dx,dz),playerFeet=p.position[1]-1.5,dy=playerFeet-mob.y,dist3=Math.hypot(horiz,dy);if(!nearest||dist3<nearest.dist3)nearest={...p,bag,dx,dz,horiz,dy,dist3,playerFeet}}let vx=0,vz=0;if(def.hostile&&nearest&&nearest.dist3<18){if(nearest.horiz>.001){vx=nearest.dx/nearest.horiz;vz=nearest.dz/nearest.horiz;mob.yaw=Math.atan2(vx,vz)}const stop=def.ranged?5.8:def.range*.78;if(nearest.horiz>stop){const nx=mob.x+vx*def.speed*dt,nz=mob.z+vz*def.speed*dt,oldH=mobGround(mob.x,mob.z),newH=mobGround(nx,nz);if(Math.abs(newH-oldH)<=1.05&&mobSpaceClear(s,nx,newH,nz,mob.type)){mob.x=nx;mob.z=nz}}const origin=[mob.x,mob.y+(mob.type==='spider'?.35:1.15),mob.z],target=[nearest.position[0],nearest.position[1]-.15,nearest.position[2]],canSee=clearLine(s,origin,target),canHit=def.ranged?(nearest.dist3<=def.range&&canSee):(nearest.horiz<=def.range&&Math.abs(nearest.dy)<=def.verticalReach&&canSee);if(canHit&&s.mode==='survival'&&now-(mob.lastAttack||0)>=def.cooldown){mob.lastAttack=now;nearest.bag.hp=Math.max(0,nearest.bag.hp-def.damage);nearest.bag.dead=nearest.bag.hp<=0;nearest.bag.lastDamage={at:now,source:def.name,damage:def.damage}}}else{const phase=(Number(mob.id.slice(1))||1)*1.713+now/5500;vx=Math.sin(phase);vz=Math.cos(phase*.83);const len=Math.hypot(vx,vz)||1;vx/=len;vz/=len;mob.yaw=Math.atan2(vx,vz);const nx=mob.x+vx*def.speed*.34*dt,nz=mob.z+vz*def.speed*.34*dt,oldH=mobGround(mob.x,mob.z),newH=mobGround(nx,nz);if(Math.abs(newH-oldH)<=1.05&&mobSpaceClear(s,nx,newH,nz,mob.type)){mob.x=nx;mob.z=nz}}mob.y=mobGround(mob.x,mob.z)}}
function mobPublic(s){ensureMobs(s);return Object.fromEntries(Object.entries(s.mobs).map(([id,m])=>[id,{id:m.id,type:m.type,x:m.x,y:m.y,z:m.z,yaw:m.yaw||0,hp:m.hp,maxHp:m.maxHp,respawnAt:m.respawnAt||0}]))}

function segmentPointDistance(a,b,p){const vx=b[0]-a[0],vy=b[1]-a[1],vz=b[2]-a[2],wx=p[0]-a[0],wy=p[1]-a[1],wz=p[2]-a[2],vv=vx*vx+vy*vy+vz*vz,t=vv?clamp((wx*vx+wy*vy+wz*vz)/vv,0,1):0;return Math.hypot(a[0]+vx*t-p[0],a[1]+vy*t-p[1],a[2]+vz*t-p[2])}
function shootArrow(s,id,bag,p,now){ensureWorld(s,now);if(!validPos(p.position)||!Array.isArray(p.direction)||p.direction.length!==3||!p.direction.every(Number.isFinite))throw Error('Некорректное направление');if(equipped(bag,p.slot)!==28)throw Error('Возьми лук в руку');const charge=clamp(Number(p.charge)||0,0,1);if(charge<.08)throw Error('Натяни лук чуть сильнее');if(s.mode==='survival')add(bag,29,-1);let [dx,dy,dz]=p.direction,len=Math.hypot(dx,dy,dz);if(len<.01)throw Error('Некорректное направление');dx/=len;dy/=len;dz/=len;const speed=9+17*charge,aid='a'+(++s.arrowSeq);s.arrows[aid]={id:aid,owner:id,ownerName:String(p.ownerName||'Игрок').slice(0,18),x:p.position[0]+dx*.55,y:p.position[1]-.2+dy*.55,z:p.position[2]+dz*.55,vx:dx*speed,vy:dy*speed,vz:dz*speed,damage:3+Math.round(5*charge),born:now,updatedAt:now,stuck:false};return {shot:true,charge,arrowId:aid}}
function projectileTick(s,now=Date.now(),players=[]){ensureWorld(s,now);for(const [id,a]of Object.entries(s.arrows)){if(now-a.born>60000){delete s.arrows[id];continue}if(a.stuck)continue;let remain=Math.min(.5,Math.max(0,(now-(a.updatedAt||now))/1000));a.updatedAt=now;while(remain>0&&!a.stuck&&s.arrows[id]){const dt=Math.min(.035,remain);remain-=dt;const from=[a.x,a.y,a.z];a.vy-=9.8*dt;const to=[a.x+a.vx*dt,a.y+a.vy*dt,a.z+a.vz*dt];let hitEntity=false;for(const m of Object.values(s.mobs||{})){if(m.hp<=0)continue;const center=[m.x,m.y+(m.type==='spider'?.25:.75),m.z],radius=m.type==='spider'?.55:.48;if(segmentPointDistance(from,to,center)<=radius){m.hp=Math.max(0,m.hp-a.damage);m.hurtAt=now;if(m.hp<=0)m.respawnAt=now+15000;delete s.arrows[id];hitEntity=true;break}}if(hitEntity)break;for(const p of players){if(!p||p.id===a.owner||!p.active||!validPos(p.position))continue;const bag=player(s,p.id,now);if(bag.dead)continue;if(segmentPointDistance(from,to,[p.position[0],p.position[1]-.75,p.position[2]])<=.52){bag.hp=Math.max(0,bag.hp-a.damage);bag.dead=bag.hp<=0;bag.lastDamage={at:now,source:a.ownerName?('Стрела: '+a.ownerName):'Стрела',damage:a.damage};delete s.arrows[id];hitEntity=true;break}}if(hitEntity)break;const segLen=Math.hypot(to[0]-from[0],to[1]-from[1],to[2]-from[2]),steps=Math.max(1,Math.ceil(segLen/.12));let blockHit=null;for(let i=1;i<=steps;i++){const t=i/steps,x=from[0]+(to[0]-from[0])*t,y=from[1]+(to[1]-from[1])*t,z=from[2]+(to[2]-from[2])*t,b=get(s,Math.floor(x),Math.floor(y),Math.floor(z));if(b&&!OPEN_DOORS.has(b)&&b!==17&&![30,43].includes(b)){blockHit=[x,y,z];break}}if(blockHit){a.x=blockHit[0];a.y=blockHit[1];a.z=blockHit[2];a.vx=a.vy=a.vz=0;a.stuck=true;a.stuckAt=now;break}a.x=to[0];a.y=to[1];a.z=to[2];if(a.y<0||a.y>=Y+6){delete s.arrows[id];break}}}}
function arrowPublic(s){ensureWorld(s);return Object.fromEntries(Object.entries(s.arrows).map(([id,a])=>[id,{id:a.id,x:a.x,y:a.y,z:a.z,vx:a.vx,vy:a.vy,vz:a.vz,stuck:!!a.stuck,born:a.born,updatedAt:a.updatedAt||a.born}]))}

function grow(s,now){s.saplings=s.saplings||{};for(const [k,t]of Object.entries(s.saplings)){if(t.at>now)continue;if(get(s,t.x,t.y,t.z)!==17){delete s.saplings[k];continue}if(![1,2].includes(get(s,t.x,t.y-1,t.z))){t.at=now+10000;continue}const parts=[];for(let dy=1;dy<=4;dy++)parts.push([t.x,t.y+dy,t.z,4]);for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=3;dy<=5;dy++)if(Math.abs(dx)+Math.abs(dz)<4)parts.push([t.x+dx,t.y+dy,t.z+dz,5]);let blocked=parts.some(([x,y,z])=>y>=Y||![0,5].includes(get(s,x,y,z)));if(blocked){t.at=now+10000;continue}s.rev++;for(const [x,y,z,b]of parts)block(s,x,y,z,b,true);for(let dy=0;dy<=4;dy++)block(s,t.x,t.y+dy,t.z,4);delete s.saplings[k]}}
const recipes=[
 {id:'planks',out:8,n:4,cost:{4:1},bench:false},{id:'bench',out:9,n:1,cost:{8:4},bench:false},{id:'chest',out:10,n:1,cost:{8:8},bench:true},{id:'door',out:11,n:1,cost:{8:6},bench:true},{id:'pick',out:14,n:1,cost:{8:3,3:3},bench:true},{id:'brick',out:7,n:4,cost:{3:4,2:2},bench:true},
 {id:'woodSword',out:22,n:1,cost:{8:2,4:1},bench:true},{id:'stoneSword',out:23,n:1,cost:{3:2,8:1},bench:true},
 {id:'bow',out:28,n:1,cost:{8:3,5:3},bench:true},{id:'arrows',out:29,n:4,cost:{3:1,8:1,5:1},bench:true}
];
const patterns={planks:[[4]],bench:[[8,8],[8,8]],chest:[[8,8,8],[8,0,8],[8,8,8]],door:[[8,8],[8,8],[8,8]],pick:[[3,3,3],[0,8,0],[0,8,8]],brick:[[3,3,3],[3,2,2]],woodSword:[[8],[8],[4]],stoneSword:[[3],[3],[8]],bow:[[0,8,5],[8,0,5],[0,8,5]],arrows:[[3],[8],[5]]};
function matchGrid(grid,size){if(![2,3].includes(size)||!Array.isArray(grid)||grid.length!==size*size||!grid.every(Number.isInteger))return null;let minX=size,minY=size,maxX=-1,maxY=-1;grid.forEach((id,i)=>{if(id){minX=Math.min(minX,i%size);minY=Math.min(minY,Math.floor(i/size));maxX=Math.max(maxX,i%size);maxY=Math.max(maxY,Math.floor(i/size))}});return recipes.find(r=>{const p=patterns[r.id];return maxX-minX+1===p[0].length&&maxY-minY+1===p.length&&p.every((row,y)=>row.every((v,x)=>grid[(minY+y)*size+minX+x]===v))})||null}
function miningTime(b,items){if([24,25,26,27].includes(b)){const base={24:900,25:1400,26:1900,27:2600}[b];return items[14]?base:base*3}return [3,7].includes(b)?(items[14]?600:2200):[4,8,9,10,11,12,15,16,18,19,20,21].includes(b)?1300:b===5?350:650}
function create(mode='creative'){const now=Date.now(),s={mode:mode==='survival'?'survival':'creative',rev:0,blocks:{},bags:{},chests:{},mobs:{},mobSeq:0,arrows:{},arrowSeq:0,worldEpoch:now-DAY_MS*.23};ensureMobs(s);return s}
function player(s,id,now){if(!s.bags[id])s.bags[id]={items:s.mode==='survival'?{13:4}:{},hp:20,food:20,tick:now,dead:false};layout(s.bags[id],s.mode);return s.bags[id]}
function layout(bag,mode){if(!Array.isArray(bag.slots)||bag.slots.length!==36){bag.slots=Array(36).fill(0);if(mode==='creative')[1,2,3,4,8,14,22,23,28].forEach((id,i)=>bag.slots[27+i]=id)}const seen=new Set();for(let i=0;i<36;i++){const id=bag.slots[i];if(id&&(seen.has(id)||(mode!=='creative'&&!count(bag,id))))bag.slots[i]=0;else if(id)seen.add(id)}const creativeIds=[1,2,3,4,5,6,7,8,9,10,11,13,14,17,22,23,24,25,26,27,28,29];for(const [item,n]of Object.entries(mode==='creative'?Object.fromEntries(creativeIds.map(i=>[i,1])):bag.items)){const id=+item;if(n>0&&!seen.has(id)){const i=bag.slots.indexOf(0);if(i>=0){bag.slots[i]=id;seen.add(id)}}}}
function equipped(bag,slot){return Number.isInteger(slot)&&slot>=0&&slot<9?bag.slots[27+slot]:0}
function count(b,id){return b.items[id]||0}function add(b,id,n){const next=count(b,id)+n;if(next<0)throw Error('Недостаточно ресурсов');if(next>9999)throw Error('Нет места для этого предмета');b.items[id]=next}
function validPos(q){return Array.isArray(q)&&q.length===3&&q.every(Number.isFinite)&&Math.abs(q[0])<1000000000&&q[1]>=0&&q[1]<Y&&Math.abs(q[2])<1000000000}
function nearby(q,x,y,z){if(!validPos(q)||![x,y,z].every(Number.isInteger)||Math.abs(x)>=1000000000||y<1||y>=Y||Math.abs(z)>=1000000000||Math.hypot(x+.5-q[0],y+.5-q[1],z+.5-q[2])>8)throw Error('Подойди ближе')}
function obstructs(q,x,y,z){return q[0]+.24>x&&q[0]-.24<x+1&&q[2]+.24>z&&q[2]-.24<z+1&&q[1]>.0+y&&q[1]-1.5<y+1}
function weaponStats(bag,slot,mode){const item=equipped(bag,slot);if(item===23&&(mode==='creative'||count(bag,23)>0))return {item,damage:6,cooldown:400,name:'Каменный меч'};if(item===22&&(mode==='creative'||count(bag,22)>0))return {item,damage:4,cooldown:440,name:'Деревянный меч'};return {item:0,damage:2,cooldown:560,name:'Кулак'}}
function canAttack(bag,stats,now){return now-(bag.lastAttack||0)>=stats.cooldown}function markAttack(bag,now){bag.lastAttack=now}
function run(s,id,p,now=Date.now(),others=[]){ensureMobs(s);ensureWorld(s,now);const bag=player(s,id,now),survival=s.mode==='survival';s.rev++;if(bag.dead&&!['respawn','tick'].includes(p.type))throw Error('Нажми «Возродиться»');let x=p.x,y=p.y,z=p.z;if(['mineStart','mine','place','door','transfer'].includes(p.type))nearby(p.position,x,y,z);
if(p.type==='tick'){let dt=Math.min(10,Math.max(0,(now-bag.tick)/1000));bag.tick=now;if(survival&&p.active&&!bag.dead){bag.food=Math.max(0,bag.food-dt/25);if(bag.food===0)bag.hp=Math.max(0,bag.hp-dt/3);else if(bag.food>=16)bag.hp=Math.min(20,bag.hp+dt/8)}}
else if(p.type==='shootBow')return shootArrow(s,id,bag,p,now);
else if(p.type==='attackMob'){if(!validPos(p.position))throw Error('Некорректная позиция');const mob=s.mobs?.[String(p.mobId||'')];if(!mob||mob.hp<=0)throw Error('Цель уже недоступна');const dist=Math.hypot(mob.x-p.position[0],mob.y+.6-(p.position[1]-.7),mob.z-p.position[2]);if(dist>3.35)throw Error('Цель слишком далеко');if(!clearLine(s,[p.position[0],p.position[1]-.2,p.position[2]],[mob.x,mob.y+.6,mob.z]))throw Error('Цель закрыта блоком');const stats=weaponStats(bag,p.slot,s.mode);if(!canAttack(bag,stats,now))throw Error('Слишком быстро');markAttack(bag,now);mob.hp=Math.max(0,mob.hp-stats.damage);mob.hurtAt=now;if(mob.hp<=0)mob.respawnAt=now+15000;return {hit:true,target:MOB_DEFS[mob.type]?.name||'Моб',damage:stats.damage,killed:mob.hp<=0}}
else if(p.type==='mineStart'){const b=get(s,x,y,z);if(!b){delete bag.mining;return {duration:0,alreadyMined:true}};const tool=equipped(bag,p.slot)===14&&(s.mode==='creative'||count(bag,14)>0)?14:0;bag.mining={key:key(x,y,z),at:now,b,tool};return {duration:miningTime(b,{14:tool===14})}}
else if(p.type==='mine'){let b=get(s,x,y,z);if(!b){delete bag.mining;return {alreadyMined:true}};if([15,16,20,21].includes(b)){y--;b=get(s,x,y,z)}if(b===10&&Object.values(s.chests[key(x,y,z)]||{}).some(n=>n>0))throw Error('Сначала забери вещи из сундука');if(survival){if(!bag.mining||bag.mining.key!==key(p.x,p.y,p.z)||bag.mining.b!==get(s,p.x,p.y,p.z)||now-bag.mining.at<miningTime(b,{14:bag.mining.tool===14&&equipped(bag,p.slot)===14}))throw Error('Блок ещё не сломан: удерживай кнопку');delete bag.mining}const naturalLeaves=b===5&&(!s.blocks[key(x,y,z)]||s.blocks[key(x,y,z)].natural===true);block(s,x,y,z,0);if([11,12,18,19].includes(b))block(s,x,y+1,z,0);if(b===10)delete s.chests[key(x,y,z)];s.drops=s.drops||{};if(b===17&&s.saplings)delete s.saplings[key(x,y,z)];const items=naturalLeaves?[5,13,17]:[[11,12,18,19].includes(b)?11:b];items.forEach((item,i)=>{s.drops[s.rev+'-'+i]={id:s.rev+'-'+i,item,n:1,x:x+.5+(i?.18:-.08),y:y+.5,z:z+.5,born:now}})}
else if(p.type==='place'){let b=p.b;if(!Number.isInteger(b)||![1,2,3,4,5,6,7,8,9,10,11,17,24,25,26,27].includes(b))throw Error('Этот предмет нельзя поставить');if(get(s,x,y,z)!==0)throw Error('Место уже занято');if(b===17&&(![1,2].includes(get(s,x,y-1,z))||y>25))throw Error('Саженцу нужна земля и место для роста');if(b===11&&(y>=30||get(s,x,y+1,z)!==0||get(s,x,y-1,z)===0))throw Error('Двери нужны опора и два свободных блока');if([p.position,...others].some(q=>obstructs(q,x,y,z)||(b===11&&obstructs(q,x,y+1,z))))throw Error('На этом месте стоит игрок');if(survival)add(bag,b,-1);const placed=b===11?(p.facing==='x'?18:11):b;block(s,x,y,z,placed);if(b===11)block(s,x,y+1,z,placed===18?20:15);if(b===10)s.chests[key(x,y,z)]={};if(b===17){s.saplings=s.saplings||{};s.saplings[key(x,y,z)]={x,y,z,at:now+45000}}}
else if(p.type==='door'){let b=get(s,x,y,z);if([15,16,20,21].includes(b)){y--;b=get(s,x,y,z)}if(![11,12,18,19].includes(b))throw Error('Здесь нет двери');if([12,19].includes(b)&&[p.position,...others].some(q=>obstructs(q,x,y,z)||obstructs(q,x,y+1,z)))throw Error('Отойди от дверного проёма');const next={11:12,12:11,18:19,19:18}[b],top={11:16,12:15,18:21,19:20}[b];block(s,x,y,z,next);block(s,x,y+1,z,top)}
else if(p.type==='craft'){const r=recipes.find(r=>r.id===p.recipe);if(!r)throw Error('Рецепт не найден');if(p.grid!==undefined&&matchGrid(p.grid,p.size)?.id!==r.id)throw Error('Неверная раскладка рецепта');if(r.bench){nearby(p.position,x,y,z);if(get(s,x,y,z)!==9)throw Error('Нужен верстак рядом')}if(survival){for(const [item,n]of Object.entries(r.cost))if(count(bag,item)<n)throw Error('Недостаточно ресурсов');for(const [item,n]of Object.entries(r.cost))add(bag,item,-n)}add(bag,r.out,r.n)}
else if(p.type==='transfer'){if(get(s,x,y,z)!==10)throw Error('Сундук уже убран');const item=p.item,n=p.amount;if(!Number.isInteger(item)||item<1||item>29||[12,15,16,18,19,20,21].includes(item)||!Number.isInteger(n)||n<1||n>64||!['put','take'].includes(p.direction))throw Error('Неверный предмет или количество');const chest=s.chests[key(x,y,z)]||(s.chests[key(x,y,z)]={});if(p.direction==='put'){if(survival||count(bag,item)>=n)add(bag,item,-n);chest[item]=(chest[item]||0)+n;if(chest[item]>9999)throw Error('Сундук полон')}else{if((chest[item]||0)<n)throw Error('В сундуке уже нет столько вещей');add(bag,item,n);chest[item]-=n}}
else if(p.type==='move'){if(!Number.isInteger(p.from)||!Number.isInteger(p.to)||p.from<0||p.from>=36||p.to<0||p.to>=36)throw Error('Неверная ячейка');[bag.slots[p.from],bag.slots[p.to]]=[bag.slots[p.to],bag.slots[p.from]];delete bag.mining}
else if(p.type==='drop'){if(!validPos(p.position)||!Array.isArray(p.direction)||p.direction.length!==3||!p.direction.every(Number.isFinite))throw Error('Некорректная позиция');const item=equipped(bag,p.slot);if(!item||(survival&&!count(bag,item)))throw Error('В выбранной ячейке нет предмета');let [dx,dy,dz]=p.direction,len=Math.hypot(dx,dy,dz);if(len<.01)throw Error('Некорректное направление');dx/=len;dy/=len;dz/=len;let [xx,yy,zz]=p.position;yy-=.35;for(let t=.1;t<=1.3;t+=.1){const nx=p.position[0]+dx*t,ny=p.position[1]-.35+dy*t,nz=p.position[2]+dz*t;if(Math.abs(nx)>=1000000000||ny<.2||ny>31.8||Math.abs(nz)>=1000000000||get(s,Math.floor(nx),Math.floor(ny),Math.floor(nz)))break;xx=nx;yy=ny;zz=nz}if(survival)add(bag,item,-1);s.drops=s.drops||{};const dk=s.rev+'-throw';s.drops[dk]={id:dk,item,n:1,x:xx,y:yy,z:zz,born:now,owner:id};delete bag.mining}
else if(p.type==='pickup'){if(!validPos(p.position))throw Error('Некорректная позиция');for(const [dk,d]of Object.entries(s.drops||{})){if(canPickup(s,d,p.position,now,id)&&count(bag,d.item)+d.n<=9999){add(bag,d.item,d.n);delete s.drops[dk]}}}
else if(p.type==='eat'){if(bag.food>=20)throw Error('Ты уже сыт');add(bag,13,-1);bag.food=Math.min(20,bag.food+5)}
else if(p.type==='fall'){if(!Number.isFinite(p.speed)||p.speed<0||p.speed>60)throw Error('Некорректное падение');if(survival)bag.hp=Math.max(0,bag.hp-Math.max(0,Math.floor((p.speed-10)*.7)))}
else if(p.type==='respawn'){bag.hp=20;bag.food=20;bag.dead=false;bag.tick=now;return {respawn:true}}
else throw Error('Неизвестное действие');layout(bag,s.mode);bag.dead=bag.hp<=0;return {}}
function dropY(s,d,now){let floor=.23;for(let y=Math.min(31,Math.floor(d.y));y>=0;y--){const b=get(s,Math.floor(d.x),y,Math.floor(d.z));if(b&&!OPEN_DOORS.has(b)&&![30,43,44].includes(b)){floor=y+1.23;break}}const t=Math.max(0,(now-d.born)/1000);return Math.max(floor,d.y+.7*t-5*t*t)}
function canPickup(s,d,q,now,collector){if((d.owner===collector&&now-d.born<2000)||now-d.born<1800)return false;const y=dropY(s,d,now),dx=d.x-q[0],dy=y-(q[1]-.8),dz=d.z-q[2],len=Math.hypot(dx,dy,dz);if(len>1.1)return false;const future=dropY(s,d,now+100);if(Math.abs(future-y)>.01)return false;for(let t=.1;t<1;t+=.1){const b=get(s,Math.floor(q[0]+dx*t),Math.floor(q[1]-.8+dy*t),Math.floor(q[2]+dz*t));if(b&&!OPEN_DOORS.has(b)&&![30,43,44].includes(b))return false}return true}
return {create,player,run,get,recipes,patterns,matchGrid,miningTime,base,height,validPos,dropY,canPickup,layout,equipped,terrain,grow,weaponStats,canAttack,markAttack,mobTick,mobPublic,MOB_DEFS,ensureMobs,projectileTick,arrowPublic,timeInfo,DAY_MS,caveAir,oreAt};
})();

// ===== EXPANSION: classic creative inventory, rails/carts, furnaces, fluids, armor, creepers and fish =====
(()=>{
const oldCreate=Game.create,oldPlayer=Game.player,oldRun=Game.run,oldProjectileTick=Game.projectileTick,oldMobPublic=Game.mobPublic;
const K=(x,y,z)=>`${x},${y},${z}`;
const NONSOLID=new Set([0,12,16,17,19,21,30,43,44]);
const CREATIVE_IDS=[1,2,3,4,5,6,7,8,9,10,11,14,17,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57];
const ARMOR_SLOT={45:0,49:0,53:0,46:1,50:1,54:1,47:2,51:2,55:2,48:3,52:3,56:3};
const ARMOR_POINTS={45:2,46:5,47:4,48:2,49:1,50:3,51:2,52:1,53:3,54:6,55:5,56:3};
const SMELT={35:38,36:39};
const FUEL={34:80000,4:15000,8:10000};
function ensureState(s){s.furnaces=s.furnaces||{};s.liquids=s.liquids||{};s.carts=s.carts||{};s.cartSeq=Number.isFinite(s.cartSeq)?s.cartSeq:0;s.fluidTickAt=s.fluidTickAt||0;s.vehicleTickAt=s.vehicleTickAt||0;return s}
function ensureBag(b){b.armor=Array.isArray(b.armor)&&b.armor.length===4?b.armor:[0,0,0,0];b.offhand=Number.isInteger(b.offhand)?b.offhand:0;b.onFireUntil=Number.isFinite(b.onFireUntil)?b.onFireUntil:0;b.fireTickAt=Number.isFinite(b.fireTickAt)?b.fireTickAt:0;b.ridingCart=b.ridingCart||null;return b}
function addItem(b,id,n){b.items=b.items||{};const v=(b.items[id]||0)+n;if(v<0)throw Error('Недостаточно ресурсов');b.items[id]=v;return v}
function takeIfSurvival(s,b,id,n=1){if(s.mode==='survival')addItem(b,id,-n)}
function giveIfSurvival(s,b,id,n=1){if(s.mode==='survival')addItem(b,id,n)}
function put(s,x,y,z,b,natural=false){s.rev++;s.blocks[K(x,y,z)]={x,y,z,b,id:s.rev,natural}}
function spawnDrop(s,item,n,x,y,z,now,owner){s.drops=s.drops||{};const id='x'+(++s.rev)+'-'+Math.random().toString(36).slice(2,6);s.drops[id]={id,item,n,x,y,z,born:now,owner}}
function near(q,x,y,z,max=8){if(!Game.validPos(q)||Math.hypot(x+.5-q[0],y+.5-q[1],z+.5-q[2])>max)throw Error('Подойди ближе')}
function solidAt(s,x,y,z){return !NONSOLID.has(Game.get(s,x,y,z))}
function clearLine(s,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2],len=Math.hypot(dx,dy,dz);if(len<.01)return true;for(let i=1,n=Math.ceil(len/.22);i<n;i++){const t=i/n;if(solidAt(s,Math.floor(a[0]+dx*t),Math.floor(a[1]+dy*t),Math.floor(a[2]+dz*t)))return false}return true}
function exposedToSky(s,x,y,z){for(let yy=Math.ceil(y+.1);yy<32;yy++){const b=Game.get(s,Math.floor(x),yy,Math.floor(z));if(b&&!NONSOLID.has(b))return false}return true}
function liquidAt(s,x,y,z){const b=Game.get(s,Math.floor(x),Math.floor(y),Math.floor(z));return b===43||b===44?b:0}
function defense(b){ensureBag(b);return b.armor.reduce((n,id)=>n+(ARMOR_POINTS[id]||0),0)}
function applyDamage(b,base,source,now=Date.now()){ensureBag(b);const d=defense(b),amount=Math.max(0,base*(1-Math.min(.8,d*.04)));b.hp=Math.max(0,b.hp-amount);b.dead=b.hp<=0;b.lastDamage={at:now,source,damage:Math.round(amount*10)/10,baseDamage:base,defense:d};return amount}
Game.armorDefense=defense;Game.applyDamage=applyDamage;
Game.ITEM_IDS={rail:30,minecart:31,furnace:32,furnaceLit:33,coal:34,rawIron:35,rawGold:36,diamond:37,ironIngot:38,goldIngot:39,bucket:40,waterBucket:41,lavaBucket:42,water:43,lava:44,shield:57};
Game.creativeCategories={building:[1,2,3,4,5,6,7,8,9,10,11,17,24,25,26,27,32],mechanisms:[9,10,11,32,40,41,42,57],transport:[30,31],combat:[22,23,28,29,45,46,47,48,49,50,51,52,53,54,55,56,57],nature:[1,2,4,5,6,17,43,44],resources:[24,25,26,27,34,35,36,37,38,39]};
Game.create=(mode='creative')=>{const s=oldCreate(mode);ensureState(s);return s};
Game.player=(s,id,now)=>ensureBag(oldPlayer(s,id,now));

function furnaceState(s,x,y,z){ensureState(s);return s.furnaces[K(x,y,z)]||(s.furnaces[K(x,y,z)]={input:{item:0,n:0},fuel:{item:0,n:0},output:{item:0,n:0},burnUntil:0,progress:0,last:Date.now()})}
function furnaceTick(s,now=Date.now()){
 ensureState(s);for(const [k,f] of Object.entries(s.furnaces)){const [x,y,z]=k.split(',').map(Number),b=Game.get(s,x,y,z);if(![32,33].includes(b)){delete s.furnaces[k];continue}const dt=Math.max(0,Math.min(2000,now-(f.last||now)));f.last=now;const recipe=SMELT[f.input.item];let burning=f.burnUntil>now;
 if(recipe&&f.input.n>0&&!burning&&f.fuel.n>0&&FUEL[f.fuel.item]){f.fuel.n--;f.burnUntil=now+FUEL[f.fuel.item];burning=true}
 if(burning&&recipe&&f.input.n>0){f.progress=(f.progress||0)+dt;if(f.progress>=10000){if(!f.output.item||f.output.item===recipe){f.input.n--;f.output.item=recipe;f.output.n=(f.output.n||0)+1;f.progress-=10000}else f.progress=9999}}
 else if(!recipe||!f.input.n)f.progress=0;
 const want=burning?33:32;if(b!==want)put(s,x,y,z,want);
 }}
Game.furnaceTick=furnaceTick;

function fluidTick(s,now=Date.now()){
 ensureState(s);if(now-s.fluidTickAt<450)return;s.fluidTickAt=now;const entries=Object.entries(s.liquids);for(const [k,q] of entries){const [x,y,z]=k.split(',').map(Number);if(Game.get(s,x,y,z)!==q.type){delete s.liquids[k];continue}const max=q.type===43?5:3;if(q.level>=max)continue;const tries=[[x,y-1,z,q.level],[x+1,y,z,q.level+1],[x-1,y,z,q.level+1],[x,y,z+1,q.level+1],[x,y,z-1,q.level+1]];for(const [nx,ny,nz,nl] of tries){if(ny<1||ny>=31||nl>max)continue;const nk=K(nx,ny,nz),cur=Game.get(s,nx,ny,nz);if(cur!==0)continue;if(s.liquids[nk])continue;put(s,nx,ny,nz,q.type);s.liquids[nk]={type:q.type,level:nl,source:false,born:now};if(ny<y)break}}
 for(const [id,d] of Object.entries(s.drops||{})){const b=Game.get(s,Math.floor(d.x),Math.floor(d.y),Math.floor(d.z));if(b===44)delete s.drops[id]}
}
Game.fluidTick=fluidTick;

function railAt(s,x,y,z){return Game.get(s,Math.floor(x),Math.floor(y),Math.floor(z))===30}
function nearestRailY(s,x,y,z){for(const yy of [Math.floor(y),Math.floor(y)-1,Math.floor(y)+1])if(railAt(s,x,yy,z))return yy;return null}
function vehicleTick(s,now=Date.now(),players=[]){ensureState(s);const dt=Math.min(.25,Math.max(0,(now-(s.vehicleTickAt||now))/1000));s.vehicleTickAt=now;if(!dt)return;for(const c of Object.values(s.carts)){let rider=null;for(const p of players){const b=Game.player(s,p.id,now);if(b.ridingCart===c.id){rider={p,b};break}}if(rider){const drive=Number(rider.p.drive)||0;if(Math.abs(drive)>.05){const a=Number(rider.p.yaw)||0,fx=Math.sin(a),fz=Math.cos(a),sign=c.axis==='x'?(fx>=0?1:-1):(fz>=0?1:-1);c.speed=Math.max(-6,Math.min(6,(c.speed||0)+drive*sign*8*dt))}}else c.speed=(c.speed||0)*Math.pow(.35,dt);if(Math.abs(c.speed)<.02){c.speed=0;continue}const step=c.speed*dt,axis=c.axis||'x',nx=c.x+(axis==='x'?step:0),nz=c.z+(axis==='z'?step:0),ry=nearestRailY(s,nx,c.y-.35,nz);if(ry===null){const alt=axis==='x'?'z':'x',ary=nearestRailY(s,c.x+(alt==='x'?Math.sign(step)*.5:0),c.y-.35,c.z+(alt==='z'?Math.sign(step)*.5:0));if(ary!==null){c.axis=alt;c.speed*=.75}else c.speed=0;continue}c.x=nx;c.z=nz;c.y=ry+.35}}
Game.vehicleTick=vehicleTick;
Game.cartPublic=s=>Object.fromEntries(Object.entries(ensureState(s).carts).map(([id,c])=>[id,{...c}]));
Game.furnacePublic=s=>JSON.parse(JSON.stringify(ensureState(s).furnaces));

Game.MOB_DEFS.creeper={name:'Крипер',hp:16,speed:1.05,damage:8,range:2.1,verticalReach:1.2,cooldown:1600,hostile:true};
Game.MOB_DEFS.cod={name:'Треска',hp:4,speed:.8,damage:0,range:0,verticalReach:0,cooldown:0,hostile:false,fish:true};
Game.MOB_DEFS.salmon={name:'Лосось',hp:5,speed:.9,damage:0,range:0,verticalReach:0,cooldown:0,hostile:false,fish:true};
function mobGround(s,x,z,start=31){const ix=Math.floor(x),iz=Math.floor(z);for(let y=Math.min(30,Math.floor(start));y>=1;y--){const b=Game.get(s,ix,y,iz);if(b&&!NONSOLID.has(b))return y+1.05}return 2.05}
function mobSpace(s,x,y,z,type){const top=type==='spider'?.42:1.65;for(let yy=Math.floor(y+.02);yy<=Math.floor(y+top-.02);yy++)if(solidAt(s,Math.floor(x),yy,Math.floor(z)))return false;return true}
function spawnMob(s,type,x,z,y=null,nightSpawn=true){s.mobs=s.mobs||{};s.mobSeq=Number.isFinite(s.mobSeq)?s.mobSeq:0;const d=Game.MOB_DEFS[type];if(!d)return null;const id='m'+(++s.mobSeq),yy=y??mobGround(s,x,z);return s.mobs[id]={id,type,x,z,y:yy,yaw:0,hp:d.hp,maxHp:d.hp,spawnX:x,spawnZ:z,lastAttack:0,respawnAt:0,nightSpawn,fuseStart:0,burning:false,airTime:0}}
function ensureFish(s){if(s.fishSeeded)return;s.fishSeeded=true;let made=0;for(let x=4;x<60&&made<8;x+=4)for(let z=4;z<60&&made<8;z+=4){for(let y=5;y>=2;y--){if(Game.get(s,x,y,z)===43){spawnMob(s,made%2?'salmon':'cod',x+.5,z+.5,y+.35,false);made++;break}}}}
function tryHostileSpawn(s,now,players){const ti=Game.timeInfo(s,now),hostiles=Object.values(s.mobs||{}).filter(m=>['zombie','skeleton','spider','creeper'].includes(m.type)&&m.hp>0);if(hostiles.length>=14||now-(s.lastHostileSpawn||0)<1500)return;s.lastHostileSpawn=now;const active=players.filter(p=>p&&p.active&&Game.validPos(p.position)&&!Game.player(s,p.id,now).dead);if(!active.length)return;for(let a=0;a<12;a++){const p=active[(s.mobSeq+a)%active.length],ang=(Math.random()*Math.PI*2),dist=7+Math.random()*9,x=p.position[0]+Math.sin(ang)*dist,z=p.position[2]+Math.cos(ang)*dist,ix=Math.floor(x),iz=Math.floor(z);let y;if(p.position[1]<Game.height(ix,iz)-1){y=Math.max(2,Math.min(29,Math.floor(p.position[1]-1.4+(Math.random()-.5)*5)));for(let k=0;k<6;k++){if(!solidAt(s,ix,y,iz)&&solidAt(s,ix,y-1,iz))break;y--}}else y=mobGround(s,x,z,Game.height(ix,iz)+2);if(!mobSpace(s,x,y,z,'zombie'))continue;const dark=!exposedToSky(s,x,y,z),allowed=ti.isNight||dark;if(!allowed)continue;const r=Math.random(),type=r<.34?'zombie':r<.58?'skeleton':r<.8?'spider':'creeper';spawnMob(s,type,x,z,y,true);break}}
function explodeCreeper(s,m,players,now){for(const p of players){if(!p||!p.active||!Game.validPos(p.position))continue;const d=Math.hypot(p.position[0]-m.x,p.position[1]-m.y,p.position[2]-m.z);if(d<4.6)applyDamage(Game.player(s,p.id,now),Math.max(0,10*(1-d/5)),'Крипер',now)}for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++)for(let dz=-2;dz<=2;dz++){if(dx*dx+dy*dy+dz*dz>5||m.y+dy<=0)continue;const x=Math.floor(m.x)+dx,y=Math.floor(m.y)+dy,z=Math.floor(m.z)+dz,b=Game.get(s,x,y,z);if(b&&![43,44].includes(b))put(s,x,y,z,0)}m.hp=0;m.respawnAt=now+20000;m.fuseStart=0}
Game.mobTick=(s,now=Date.now(),players=[])=>{ensureState(s);ensureFish(s);tryHostileSpawn(s,now,players);const last=s.mobTickAt2||now,dt=Math.min(.55,Math.max(0,(now-last)/1000));s.mobTickAt2=now;if(!dt)return;const ti=Game.timeInfo(s,now);for(const mob of Object.values(s.mobs||{})){const def=Game.MOB_DEFS[mob.type];if(!def)continue;if(mob.hp<=0){if(!def.hostile&&!def.fish&&now>=(mob.respawnAt||0)){mob.hp=def.hp;mob.x=mob.spawnX;mob.z=mob.spawnZ;mob.y=mobGround(s,mob.x,mob.z);mob.respawnAt=0}continue}
 if(def.fish){const water=liquidAt(s,mob.x,mob.y,mob.z)===43;if(!water){mob.airTime=(mob.airTime||0)+dt;if(mob.airTime>3)mob.hp=Math.max(0,mob.hp-dt*3);mob.y-=dt*.8;continue}mob.airTime=0;const ph=(Number(mob.id.slice(1))||1)+now/1400,mx=Math.sin(ph),mz=Math.cos(ph*.77),nx=mob.x+mx*def.speed*dt,nz=mob.z+mz*def.speed*dt,ny=mob.y+Math.sin(ph*.43)*.12;if(liquidAt(s,nx,ny,nz)===43){mob.x=nx;mob.z=nz;mob.y=ny;mob.yaw=Math.atan2(mx,mz)}continue}
 const water=liquidAt(s,mob.x,mob.y+.15,mob.z)===43,lava=liquidAt(s,mob.x,mob.y+.15,mob.z)===44,openSun=!ti.isNight&&ti.light>.68&&exposedToSky(s,mob.x,mob.y+.6,mob.z);if(water){mob.burning=false;mob.burnAcc=0}else if(lava){mob.burning=true;mob.hp=Math.max(0,mob.hp-dt*5)}else if(openSun&&['zombie','skeleton','creeper'].includes(mob.type)){mob.burning=true;mob.burnAcc=(mob.burnAcc||0)+dt;if(mob.burnAcc>=1){mob.hp=Math.max(0,mob.hp-2);mob.burnAcc=0}}else mob.burning=false;
 const dark=!exposedToSky(s,mob.x,mob.y+.4,mob.z),aggressive=def.hostile&&(mob.type!=='spider'||ti.isNight||dark)&&(ti.isNight||dark||mob.type==='spider');let nearest=null;for(const p of players){if(!p||!p.active||!Game.validPos(p.position))continue;const bag=Game.player(s,p.id,now);if(bag.dead)continue;const dx=p.position[0]-mob.x,dz=p.position[2]-mob.z,horiz=Math.hypot(dx,dz),dy=(p.position[1]-1.5)-mob.y,dist3=Math.hypot(horiz,dy);if(!nearest||dist3<nearest.dist3)nearest={p,bag,dx,dz,horiz,dy,dist3}}
 if(aggressive&&nearest&&nearest.dist3<18){const vx=nearest.horiz>.001?nearest.dx/nearest.horiz:0,vz=nearest.horiz>.001?nearest.dz/nearest.horiz:0;mob.yaw=Math.atan2(vx,vz);if(mob.type==='creeper'&&nearest.horiz<2.15&&Math.abs(nearest.dy)<1.3&&clearLine(s,[mob.x,mob.y+.8,mob.z],nearest.p.position)){mob.fuseStart=mob.fuseStart||now;if(now-mob.fuseStart>=1500){explodeCreeper(s,mob,players,now);continue}}else mob.fuseStart=0;const stop=def.ranged?5.8:mob.type==='creeper'?1.75:def.range*.78;if(nearest.horiz>stop){const nx=mob.x+vx*def.speed*dt,nz=mob.z+vz*def.speed*dt,ny=mobGround(s,nx,nz,mob.y+2);if(Math.abs(ny-mob.y)<=1.05&&mobSpace(s,nx,ny,nz,mob.type)){mob.x=nx;mob.z=nz;mob.y=ny}}const canSee=clearLine(s,[mob.x,mob.y+(mob.type==='spider'?.3:1.1),mob.z],[nearest.p.position[0],nearest.p.position[1]-.2,nearest.p.position[2]]),canHit=def.ranged?(nearest.dist3<=def.range&&canSee):(nearest.horiz<=def.range&&Math.abs(nearest.dy)<=def.verticalReach&&canSee);if(canHit&&mob.type!=='creeper'&&s.mode==='survival'&&now-(mob.lastAttack||0)>=def.cooldown){mob.lastAttack=now;applyDamage(nearest.bag,def.damage,def.name,now)}}else{mob.fuseStart=0;const ph=(Number(mob.id.slice(1))||1)*1.71+now/5500,vx=Math.sin(ph),vz=Math.cos(ph*.83),l=Math.hypot(vx,vz)||1,nx=mob.x+vx/l*def.speed*.28*dt,nz=mob.z+vz/l*def.speed*.28*dt,ny=mobGround(s,nx,nz,mob.y+2);if(Math.abs(ny-mob.y)<=1.05&&mobSpace(s,nx,ny,nz,mob.type)){mob.x=nx;mob.z=nz;mob.y=ny;mob.yaw=Math.atan2(vx,vz)}}}}
Game.mobPublic=s=>Object.fromEntries(Object.entries(s.mobs||{}).map(([id,m])=>[id,{id:m.id,type:m.type,x:m.x,y:m.y,z:m.z,yaw:m.yaw||0,hp:m.hp,maxHp:m.maxHp,burning:!!m.burning,fuse:!!m.fuseStart,shadow:!exposedToSky(s,m.x,m.y+.5,m.z)}]));

Game.projectileTick=(s,now=Date.now(),players=[])=>{const before=new Map(players.map(p=>[p.id,Game.player(s,p.id,now).hp]));oldProjectileTick(s,now,players);for(const p of players){const b=Game.player(s,p.id,now),prev=before.get(p.id);if(Number.isFinite(prev)&&b.hp<prev){const raw=prev-b.hp;b.hp=prev;applyDamage(b,raw,b.lastDamage?.source||'Стрела',now)}}};

Game.run=(s,id,p,now=Date.now(),others=[])=>{ensureState(s);const bag=ensureBag(Game.player(s,id,now));const beforeHp=bag.hp;let x=p.x,y=p.y,z=p.z;
 if(p.type==='creativeGive'){if(s.mode!=='creative')throw Error('Только в творческом режиме');if(!CREATIVE_IDS.includes(p.item)||!Number.isInteger(p.to)||p.to<0||p.to>=36)throw Error('Неверный предмет');bag.slots[p.to]=p.item;return {given:true}}
 if(p.type==='equipArmor'){const item=bag.slots[p.from],slot=ARMOR_SLOT[item];if(slot===undefined||slot!==p.armorSlot)throw Error('Эта броня не подходит в этот слот');const old=bag.armor[slot]||0;bag.armor[slot]=item;bag.slots[p.from]=old;return {armor:true,defense:defense(bag)}}
 if(p.type==='unequipArmor'){const slot=p.armorSlot;if(!Number.isInteger(slot)||slot<0||slot>3||!bag.armor[slot])throw Error('Слот пуст');const to=bag.slots.indexOf(0);if(to<0)throw Error('Нет свободной ячейки');bag.slots[to]=bag.armor[slot];bag.armor[slot]=0;return {armor:true,defense:defense(bag)}}
 if(p.type==='equipOffhand'){const item=bag.slots[p.from];if(item!==57)throw Error('Во вторую руку сейчас можно взять щит');const old=bag.offhand||0;bag.offhand=item;bag.slots[p.from]=old;return {offhand:true}}
 if(p.type==='unequipOffhand'){if(!bag.offhand)throw Error('Вторая рука пуста');const to=bag.slots.indexOf(0);if(to<0)throw Error('Нет свободной ячейки');bag.slots[to]=bag.offhand;bag.offhand=0;return {offhand:true}}
 if(p.type==='furnaceTransfer'){near(p.position,x,y,z);const f=furnaceState(s,x,y,z);if(![32,33].includes(Game.get(s,x,y,z)))throw Error('Печки здесь нет');const slot=String(p.furnaceSlot||''),dir=p.direction;if(!['input','fuel','output'].includes(slot)||!['put','take'].includes(dir))throw Error('Неверный слот');if(dir==='put'){if(slot==='output')throw Error('В результат нельзя класть предмет');const item=p.item;if(slot==='input'&&!SMELT[item])throw Error('Этот предмет нельзя переплавить');if(slot==='fuel'&&!FUEL[item])throw Error('Это не топливо');const target=f[slot];if(target.item&&target.item!==item)throw Error('Слот занят другим предметом');takeIfSurvival(s,bag,item,1);target.item=item;target.n=(target.n||0)+1}else{const target=f[slot];if(!target.n)throw Error('Слот пуст');giveIfSurvival(s,bag,target.item,1);target.n--;if(!target.n)target.item=0}furnaceTick(s,now);return {furnace:true}}
 if(p.type==='bucket'){near(p.position,x,y,z);const held=Game.equipped(bag,p.slot);const b=Game.get(s,x,y,z);if(held===40&&[43,44].includes(b)){put(s,x,y,z,0);delete s.liquids[K(x,y,z)];if(s.mode==='survival'){addItem(bag,40,-1);addItem(bag,b===43?41:42,1)}else bag.slots[27+p.slot]=b===43?41:42;return {bucket:true}}if([41,42].includes(held)){const type=held===41?43:44;if(b!==0)throw Error('Здесь уже есть блок');put(s,x,y,z,type);s.liquids[K(x,y,z)]={type,level:0,source:true,born:now};if(s.mode==='survival'){addItem(bag,held,-1);addItem(bag,40,1)}else bag.slots[27+p.slot]=40;fluidTick(s,now);return {bucket:true}}throw Error('Возьми пустое или наполненное ведро')}
 if(p.type==='spawnCart'){near(p.position,x,y,z);if(Game.get(s,x,y,z)!==30)throw Error('Вагонетку нужно поставить на рельсы');takeIfSurvival(s,bag,31,1);const cid='c'+(++s.cartSeq);s.carts[cid]={id:cid,x:x+.5,y:y+.35,z:z+.5,axis:p.axis==='z'?'z':'x',speed:0};return {cartId:cid}}
 if(p.type==='rideCart'){const c=s.carts[p.cartId];if(!c)throw Error('Вагонетки уже нет');if(Math.hypot(c.x-p.position[0],c.y-p.position[1]+1.2,c.z-p.position[2])>3)throw Error('Подойди ближе');bag.ridingCart=bag.ridingCart===c.id?null:c.id;return {riding:bag.ridingCart}}
 if(p.type==='pushCart'){const c=s.carts[p.cartId];if(!c)throw Error('Вагонетки уже нет');if(Math.hypot(c.x-p.position[0],c.y-p.position[1]+1.2,c.z-p.position[2])>3)throw Error('Подойди ближе');const d=p.direction||[0,0,1];c.speed=Math.max(-6,Math.min(6,(c.speed||0)+(c.axis==='x'?Math.sign(d[0]||1):Math.sign(d[2]||1))*2.5));return {pushed:true}}
 if(p.type==='place'&&[30,32,43,44].includes(p.b)){near(p.position,x,y,z);if(Game.get(s,x,y,z)!==0)throw Error('Место уже занято');if(!solidAt(s,x,y-1,z))throw Error('Нужна опора');takeIfSurvival(s,bag,p.b,1);put(s,x,y,z,p.b);if(p.b===32)furnaceState(s,x,y,z);if([43,44].includes(p.b))s.liquids[K(x,y,z)]={type:p.b,level:0,source:true,born:now};return {placed:true}}
 if(p.type==='mine'&&[32,33].includes(Game.get(s,x,y,z))){const f=s.furnaces[K(x,y,z)];if(f&&(f.input.n||f.fuel.n||f.output.n))throw Error('Сначала забери вещи из печки')}
 const minedFurnaceKey=(p.type==='mine'&&[32,33].includes(Game.get(s,x,y,z)))?K(x,y,z):null;const beforeDrops=new Set(Object.keys(s.drops||{}));const r=oldRun(s,id,p,now,others)||{};
 if(p.type==='mine'){const oldb=p&&Number.isInteger(p.x)?null:null;for(const [dk,d] of Object.entries(s.drops||{}))if(!beforeDrops.has(dk)){if(d.item===24)d.item=34;else if(d.item===25)d.item=35;else if(d.item===26)d.item=36;else if(d.item===27)d.item=37;else if(d.item===33)d.item=32}if(minedFurnaceKey)delete s.furnaces[minedFurnaceKey]}
 if(p.type==='fall'&&bag.hp<beforeHp){const raw=beforeHp-bag.hp;bag.hp=beforeHp;applyDamage(bag,raw,'Падение',now)}
 if(p.type==='tick'){furnaceTick(s,now);fluidTick(s,now);const pos=p.position;if(Game.validPos(pos)){const feet=liquidAt(s,pos[0],pos[1]-1.2,pos[2]),body=liquidAt(s,pos[0],pos[1]-.5,pos[2]);if(feet===43||body===43){bag.onFireUntil=0;bag.fireTickAt=0}if(feet===44||body===44)bag.onFireUntil=Math.max(bag.onFireUntil,now+5000);if(bag.onFireUntil>now&&s.mode==='survival'&&now-(bag.fireTickAt||0)>1000){bag.fireTickAt=now;applyDamage(bag,2,'Огонь',now)}}}
 return r};

const extraRecipes=[
 {id:'rails',out:30,n:8,cost:{38:6,8:1},bench:true,pat:[[38,0,38],[38,8,38],[38,0,38]]},
 {id:'minecart',out:31,n:1,cost:{38:5},bench:true,pat:[[38,0,38],[38,38,38]]},
 {id:'furnace',out:32,n:1,cost:{3:8},bench:true,pat:[[3,3,3],[3,0,3],[3,3,3]]},
 {id:'bucket',out:40,n:1,cost:{38:3},bench:true,pat:[[38,0,38],[0,38,0]]},
 {id:'shield',out:57,n:1,cost:{8:6,38:1},bench:true,pat:[[8,38,8],[8,8,8],[0,8,0]]},
 {id:'ironHelmet',out:45,n:1,cost:{38:5},bench:true,pat:[[38,38,38],[38,0,38]]},
 {id:'ironChest',out:46,n:1,cost:{38:8},bench:true,pat:[[38,0,38],[38,38,38],[38,38,38]]},
 {id:'ironLegs',out:47,n:1,cost:{38:7},bench:true,pat:[[38,38,38],[38,0,38],[38,0,38]]},
 {id:'ironBoots',out:48,n:1,cost:{38:4},bench:true,pat:[[38,0,38],[38,0,38]]},
 {id:'goldHelmet',out:49,n:1,cost:{39:5},bench:true,pat:[[39,39,39],[39,0,39]]},
 {id:'goldChest',out:50,n:1,cost:{39:8},bench:true,pat:[[39,0,39],[39,39,39],[39,39,39]]},
 {id:'goldLegs',out:51,n:1,cost:{39:7},bench:true,pat:[[39,39,39],[39,0,39],[39,0,39]]},
 {id:'goldBoots',out:52,n:1,cost:{39:4},bench:true,pat:[[39,0,39],[39,0,39]]},
 {id:'diamondHelmet',out:53,n:1,cost:{37:5},bench:true,pat:[[37,37,37],[37,0,37]]},
 {id:'diamondChest',out:54,n:1,cost:{37:8},bench:true,pat:[[37,0,37],[37,37,37],[37,37,37]]},
 {id:'diamondLegs',out:55,n:1,cost:{37:7},bench:true,pat:[[37,37,37],[37,0,37],[37,0,37]]},
 {id:'diamondBoots',out:56,n:1,cost:{37:4},bench:true,pat:[[37,0,37],[37,0,37]]}
];
for(const r of extraRecipes){if(!Game.recipes.some(x=>x.id===r.id)){Game.recipes.push({id:r.id,out:r.out,n:r.n,cost:r.cost,bench:r.bench});Game.patterns[r.id]=r.pat}}
Game.CREATIVE_IDS=CREATIVE_IDS;Game.ARMOR_SLOT=ARMOR_SLOT;Game.ARMOR_POINTS=ARMOR_POINTS;Game.exposedToSky=exposedToSky;

})();

module.exports=Game;
