'use strict';
// Shared, deterministic game rules. Server state is authoritative.
const Game=(()=>{
const N=64,Y=32,idx=(x,y,z)=>x+N*(z+N*y),key=(x,y,z)=>`${x},${y},${z}`;
const height=(x,z)=>Math.floor(6+2.5*Math.sin(x*.13)+2*Math.cos(z*.16)+1.3*Math.sin((x+z)*.22));
const base=new Uint8Array(N*N*Y);function put(x,y,z,b){if(x>=0&&z>=0&&y>=0&&x<N&&z<N&&y<Y)base[idx(x,y,z)]=b}
for(let x=0;x<N;x++)for(let z=0;z<N;z++){let h=height(x,z);for(let y=0;y<=h;y++)put(x,y,z,y===h?(h<5?6:1):y>h-3?2:3)}
for(let x=4;x<60;x+=5)for(let z=4;z<60;z+=5)if(Math.sin(x*23+z*37)>.15&&Math.hypot(x-32,z-32)>6){let h=height(x,z);if(h<5)continue;for(let y=h+1;y<h+5;y++)put(x,y,z,4);for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++)for(let c=3;c<=5;c++)if(Math.abs(a)+Math.abs(b)<4)put(x+a,h+c,z+b,5);put(x,h+3,z,4)}
function terrain(x,y,z){if(y<0||y>=32)return 0;if(x>=0&&x<64&&z>=0&&z<64)return base[idx(x,y,z)];const h=height(x,z);if(y<=h)return y===h?(h<5?6:1):y>h-3?2:3;if(y>17)return 0;let b=0;for(let tx=4+5*Math.ceil((x-6)/5);tx<=x+2;tx+=5)for(let tz=4+5*Math.ceil((z-6)/5);tz<=z+2;tz+=5){if(tx>=0&&tx<64&&tz>=0&&tz<64&&(tx<4||tx>=60||tz<4||tz>=60))continue;if(Math.sin(tx*23+tz*37)<=.15||Math.hypot(tx-32,tz-32)<=6)continue;const th=height(tx,tz),dy=y-th;if(th<5)continue;if(tx===x&&tz===z&&dy>=1&&dy<=4)b=4;if(Math.abs(x-tx)+Math.abs(z-tz)<4&&dy>=3&&dy<=5)b=5;if(tx===x&&tz===z&&dy===3)b=4}return b}
function grow(s,now){s.saplings=s.saplings||{};for(const [k,t]of Object.entries(s.saplings)){if(t.at>now)continue;if(get(s,t.x,t.y,t.z)!==17){delete s.saplings[k];continue}if(![1,2].includes(get(s,t.x,t.y-1,t.z))){t.at=now+10000;continue}const parts=[];for(let dy=1;dy<=4;dy++)parts.push([t.x,t.y+dy,t.z,4]);for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=3;dy<=5;dy++)if(Math.abs(dx)+Math.abs(dz)<4)parts.push([t.x+dx,t.y+dy,t.z+dz,5]);let blocked=parts.some(([x,y,z])=>y>=32||![0,5].includes(get(s,x,y,z)));if(blocked){t.at=now+10000;continue}s.rev++;for(const [x,y,z,b]of parts)block(s,x,y,z,b,true);for(let dy=0;dy<=4;dy++)block(s,t.x,t.y+dy,t.z,4);delete s.saplings[k]}}
const recipes=[{id:'planks',out:8,n:4,cost:{4:1},bench:false},{id:'bench',out:9,n:1,cost:{8:4},bench:false},{id:'chest',out:10,n:1,cost:{8:8},bench:true},{id:'door',out:11,n:1,cost:{8:6},bench:true},{id:'pick',out:14,n:1,cost:{8:3,3:3},bench:true},{id:'brick',out:7,n:4,cost:{3:4,2:2},bench:true}];
const patterns={planks:[[4]],bench:[[8,8],[8,8]],chest:[[8,8,8],[8,0,8],[8,8,8]],door:[[8,8],[8,8],[8,8]],pick:[[3,3,3],[0,8,0],[0,8,8]],brick:[[3,3,3],[3,2,2]]};
function matchGrid(grid,size){if(![2,3].includes(size)||!Array.isArray(grid)||grid.length!==size*size||!grid.every(Number.isInteger))return null;let minX=size,minY=size,maxX=-1,maxY=-1;grid.forEach((id,i)=>{if(id){minX=Math.min(minX,i%size);minY=Math.min(minY,Math.floor(i/size));maxX=Math.max(maxX,i%size);maxY=Math.max(maxY,Math.floor(i/size))}});return recipes.find(r=>{const p=patterns[r.id];return maxX-minX+1===p[0].length&&maxY-minY+1===p.length&&p.every((row,y)=>row.every((v,x)=>grid[(minY+y)*size+minX+x]===v))})||null}
function miningTime(b,items){return [3,7].includes(b)?(items[14]?600:2200):[4,8,9,10,11,12,15,16,18,19,20,21].includes(b)?1300:b===5?350:650}
function create(mode='creative'){return {mode:mode==='survival'?'survival':'creative',rev:0,blocks:{},bags:{},chests:{}}}
function player(s,id,now){if(!s.bags[id])s.bags[id]={items:s.mode==='survival'?{13:4}:{},hp:20,food:20,tick:now,dead:false};layout(s.bags[id],s.mode);return s.bags[id]}
function layout(bag,mode){if(!Array.isArray(bag.slots)||bag.slots.length!==36){bag.slots=Array(36).fill(0);if(mode==='creative')[1,2,3,4,8,9,10,11,14].forEach((id,i)=>bag.slots[27+i]=id)}const seen=new Set();for(let i=0;i<36;i++){const id=bag.slots[i];if(id&&(seen.has(id)||(mode!=='creative'&&!count(bag,id))))bag.slots[i]=0;else if(id)seen.add(id)}for(const [item,n]of Object.entries(mode==='creative'?Object.fromEntries([1,2,3,4,5,6,7,8,9,10,11,13,14,17].map(i=>[i,1])):bag.items)){const id=+item;if(n>0&&!seen.has(id)){const i=bag.slots.indexOf(0);if(i>=0){bag.slots[i]=id;seen.add(id)}}}}
function equipped(bag,slot){return Number.isInteger(slot)&&slot>=0&&slot<9?bag.slots[27+slot]:0}
function get(s,x,y,z){return s.blocks[key(x,y,z)]?.b??terrain(x,y,z)}
function block(s,x,y,z,b,natural=false){s.blocks[key(x,y,z)]={x,y,z,b,id:s.rev,natural}}
function count(b,id){return b.items[id]||0}function add(b,id,n){const next=count(b,id)+n;if(next<0)throw Error('Недостаточно ресурсов');if(next>9999)throw Error('Нет места для этого предмета');b.items[id]=next}
function validPos(q){return Array.isArray(q)&&q.length===3&&q.every(Number.isFinite)&&Math.abs(q[0])<1000000000&&q[1]>=0&&q[1]<32&&Math.abs(q[2])<1000000000}
function nearby(q,x,y,z){if(!validPos(q)||![x,y,z].every(Number.isInteger)||Math.abs(x)>=1000000000||y<1||y>=32||Math.abs(z)>=1000000000||Math.hypot(x+.5-q[0],y+.5-q[1],z+.5-q[2])>8)throw Error('Подойди ближе')}
function obstructs(q,x,y,z){return q[0]+.24>x&&q[0]-.24<x+1&&q[2]+.24>z&&q[2]-.24<z+1&&q[1]>.0+y&&q[1]-1.5<y+1}
function run(s,id,p,now=Date.now(),others=[]){const bag=player(s,id,now),survival=s.mode==='survival';s.rev++;if(bag.dead&&!['respawn','tick'].includes(p.type))throw Error('Нажми «Возродиться»');let x=p.x,y=p.y,z=p.z;
if(['mineStart','mine','place','door','transfer'].includes(p.type))nearby(p.position,x,y,z);
if(p.type==='tick'){let dt=Math.min(10,Math.max(0,(now-bag.tick)/1000));bag.tick=now;if(survival&&p.active&&!bag.dead){bag.food=Math.max(0,bag.food-dt/25);if(bag.food===0)bag.hp=Math.max(0,bag.hp-dt/3);else if(bag.food>=16)bag.hp=Math.min(20,bag.hp+dt/8)}}
else if(p.type==='mineStart'){const b=get(s,x,y,z);if(!b)throw Error('Блок уже добыт');const tool=equipped(bag,p.slot)===14&&(s.mode==='creative'||count(bag,14)>0)?14:0;bag.mining={key:key(x,y,z),at:now,b,tool};return {duration:miningTime(b,{14:tool===14})}}
else if(p.type==='mine'){let b=get(s,x,y,z);if(!b)throw Error('Блок уже добыт');if([15,16,20,21].includes(b)){y--;b=get(s,x,y,z)}if(b===10&&Object.values(s.chests[key(x,y,z)]||{}).some(n=>n>0))throw Error('Сначала забери вещи из сундука');if(survival){if(!bag.mining||bag.mining.key!==key(p.x,p.y,p.z)||bag.mining.b!==get(s,p.x,p.y,p.z)||now-bag.mining.at<miningTime(b,{14:bag.mining.tool===14&&equipped(bag,p.slot)===14}))throw Error('Блок ещё не сломан: удерживай кнопку');delete bag.mining;}const naturalLeaves=b===5&&(!s.blocks[key(x,y,z)]||s.blocks[key(x,y,z)].natural===true);block(s,x,y,z,0);if([11,12,18,19].includes(b))block(s,x,y+1,z,0);if(b===10)delete s.chests[key(x,y,z)];s.drops=s.drops||{};if(b===17&&s.saplings)delete s.saplings[key(x,y,z)];const items=naturalLeaves?[5,13,17]:[[11,12,18,19].includes(b)?11:b];items.forEach((item,i)=>{s.drops[s.rev+'-'+i]={id:s.rev+'-'+i,item,n:1,x:x+.5+(i?.18:-.08),y:y+.5,z:z+.5,born:now}})}
else if(p.type==='place'){let b=p.b;if(!Number.isInteger(b)||![1,2,3,4,5,6,7,8,9,10,11,17].includes(b))throw Error('Этот предмет нельзя поставить');if(get(s,x,y,z)!==0)throw Error('Место уже занято');if(b===17&&(![1,2].includes(get(s,x,y-1,z))||y>25))throw Error('Саженцу нужна земля и место для роста');if(b===11&&(y>=30||get(s,x,y+1,z)!==0||get(s,x,y-1,z)===0))throw Error('Двери нужны опора и два свободных блока');if([p.position,...others].some(q=>obstructs(q,x,y,z)||(b===11&&obstructs(q,x,y+1,z))))throw Error('На этом месте стоит игрок');if(survival)add(bag,b,-1);const placed=b===11?(p.facing==='x'?18:11):b;block(s,x,y,z,placed);if(b===11)block(s,x,y+1,z,placed===18?20:15);if(b===10)s.chests[key(x,y,z)]={};if(b===17){s.saplings=s.saplings||{};s.saplings[key(x,y,z)]={x,y,z,at:now+45000}}}
else if(p.type==='door'){let b=get(s,x,y,z);if([15,16,20,21].includes(b)){y--;b=get(s,x,y,z)}if(![11,12,18,19].includes(b))throw Error('Здесь нет двери');if([12,19].includes(b)&&[p.position,...others].some(q=>obstructs(q,x,y,z)||obstructs(q,x,y+1,z)))throw Error('Отойди от дверного проёма');const next={11:12,12:11,18:19,19:18}[b],top={11:16,12:15,18:21,19:20}[b];block(s,x,y,z,next);block(s,x,y+1,z,top)}
else if(p.type==='craft'){const r=recipes.find(r=>r.id===p.recipe);if(!r)throw Error('Рецепт не найден');if(p.grid!==undefined&&matchGrid(p.grid,p.size)?.id!==r.id)throw Error('Неверная раскладка рецепта');if(r.bench){nearby(p.position,x,y,z);if(get(s,x,y,z)!==9)throw Error('Нужен верстак рядом')}if(survival){for(const [item,n]of Object.entries(r.cost))if(count(bag,item)<n)throw Error('Недостаточно ресурсов');for(const [item,n]of Object.entries(r.cost))add(bag,item,-n)}add(bag,r.out,r.n)}
else if(p.type==='transfer'){if(get(s,x,y,z)!==10)throw Error('Сундук уже убран');const item=p.item,n=p.amount;if(!Number.isInteger(item)||item<1||(item>14&&item!==17)||item===12||!Number.isInteger(n)||n<1||n>64||!['put','take'].includes(p.direction))throw Error('Неверный предмет или количество');const chest=s.chests[key(x,y,z)]||(s.chests[key(x,y,z)]={});if(p.direction==='put'){if(survival||count(bag,item)>=n)add(bag,item,-n);chest[item]=(chest[item]||0)+n;if(chest[item]>9999)throw Error('Сундук полон')}else{if((chest[item]||0)<n)throw Error('В сундуке уже нет столько вещей');add(bag,item,n);chest[item]-=n}}
else if(p.type==='move'){if(!Number.isInteger(p.from)||!Number.isInteger(p.to)||p.from<0||p.from>=36||p.to<0||p.to>=36)throw Error('Неверная ячейка');[bag.slots[p.from],bag.slots[p.to]]=[bag.slots[p.to],bag.slots[p.from]];delete bag.mining}
else if(p.type==='drop'){if(!validPos(p.position)||!Array.isArray(p.direction)||p.direction.length!==3||!p.direction.every(Number.isFinite))throw Error('Некорректная позиция');const item=equipped(bag,p.slot);if(!item||(survival&&!count(bag,item)))throw Error('В выбранной ячейке нет предмета');let [dx,dy,dz]=p.direction,len=Math.hypot(dx,dy,dz);if(len<.01)throw Error('Некорректное направление');dx/=len;dy/=len;dz/=len;let [x,y,z]=p.position;y-=.35;for(let t=.1;t<=1.3;t+=.1){const nx=p.position[0]+dx*t,ny=p.position[1]-.35+dy*t,nz=p.position[2]+dz*t;if(Math.abs(nx)>=1000000000||ny<.2||ny>31.8||Math.abs(nz)>=1000000000||get(s,Math.floor(nx),Math.floor(ny),Math.floor(nz)))break;x=nx;y=ny;z=nz}if(survival)add(bag,item,-1);s.drops=s.drops||{};const key=s.rev+'-throw';s.drops[key]={id:key,item,n:1,x,y,z,born:now,owner:id};delete bag.mining}
else if(p.type==='pickup'){if(!validPos(p.position))throw Error('Некорректная позиция');for(const [key,d]of Object.entries(s.drops||{})){if(canPickup(s,d,p.position,now,id)&&count(bag,d.item)+d.n<=9999){add(bag,d.item,d.n);delete s.drops[key]}}}
else if(p.type==='eat'){if(bag.food>=20)throw Error('Ты уже сыт');add(bag,13,-1);bag.food=Math.min(20,bag.food+5)}
else if(p.type==='fall'){if(!Number.isFinite(p.speed)||p.speed<0||p.speed>60)throw Error('Некорректное падение');if(survival)bag.hp=Math.max(0,bag.hp-Math.max(0,Math.floor((p.speed-10)*.7)))}
else if(p.type==='respawn'){bag.hp=20;bag.food=20;bag.dead=false;bag.tick=now;return {respawn:true}}
else throw Error('Неизвестное действие');layout(bag,s.mode);bag.dead=bag.hp<=0;return {}}
function dropY(s,d,now){let floor=.23;for(let y=Math.min(31,Math.floor(d.y));y>=0;y--){const b=get(s,Math.floor(d.x),y,Math.floor(d.z));if(b&&![12,16,19,21].includes(b)){floor=y+1.23;break}}const t=Math.max(0,(now-d.born)/1000);return Math.max(floor,d.y+.7*t-5*t*t)}
function canPickup(s,d,q,now,collector){if((d.owner===collector&&now-d.born<2000)||now-d.born<1800)return false;const y=dropY(s,d,now),dx=d.x-q[0],dy=y-(q[1]-.8),dz=d.z-q[2],len=Math.hypot(dx,dy,dz);if(len>1.1)return false;const future=dropY(s,d,now+100);if(Math.abs(future-y)>.01)return false;for(let t=.1;t<1;t+=.1){const b=get(s,Math.floor(q[0]+dx*t),Math.floor(q[1]-.8+dy*t),Math.floor(q[2]+dz*t));if(b&&![12,16,19,21].includes(b))return false}return true}
return {create,player,run,get,recipes,patterns,matchGrid,miningTime,base,height,validPos,dropY,canPickup,layout,equipped,terrain,grow};})();

module.exports = Game;
